AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    VPCCIDR:
        Type: String
        Default: "10.17.0.0/16"
        Description: The CIDR range to assign to the VPC.
        AllowedPattern: "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/[0-9]{1,2}"
        ConstraintDescription: An IPv4 block in CIDR notation is required, e.g. 10.17.0.0/16
    SubnetAZ:
        Type: AWS::EC2::AvailabilityZone::Name
        Default: us-west-2a
        Description: The availability zone to assign to the subnet.
    SubnetCIDR:
        Type: String
        Default: "10.17.0.0/16"
        Description: The CIDR range to assign to the subnet.
        AllowedPattern: "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/[0-9]{1,2}"
        ConstraintDescription: An IPv4 block in CIDR notation is required, e.g. 10.17.0.0/16

Resources:
  AdamCloudVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      InstanceTenancy: dedicated
      Tags:
      - Key: Name
        Value: AdamCloudVPC

  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AdamCloudVPC
      CidrBlock: !Ref SubnetCIDR
      AvailabilityZone: !Ref SubnetAZ
      Tags:
      - Key: foo
        Value: bar
